[package]
name = "chiral-network-core"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = "0.3.31"
libp2p = { version = "0.56.0", features = ["kad", "tcp", "tls", "yamux", "noise", "tokio"] }
log = "0.4.28"
tokio = { version = "1.47.1", features = ["rt"] }
