name: Build Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.12'

    - name: Install dependencies
      run: npm install

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: apt-get update
      run: sudo apt-get update

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y libglib2.0-dev pkg-config build-essential libgtk-3-dev curl libssl-dev libsoup-3.0 javascriptcoregtk-4.1 webkit2gtk-4.1 libayatana-appindicator3-1

    - name: Build frontend
      run: npm run build

    - name: Build backend
      run: cd src-tauri && cargo build
