name: NAT Traversal Tests

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'src-tauri/**'
      - 'src/lib/stores.ts'
      - 'src/pages/Settings.svelte'
      - 'src/pages/Network.svelte'
      - '.github/workflows/nat-tests.yml'
  workflow_dispatch:

jobs:
  nat-integration-tests:
    name: NAT Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libjavascriptcoregtk-4.1-dev libsoup-3.0-dev \
            libglib2.0-dev pkg-config build-essential libgtk-3-dev curl libssl-dev \
            libayatana-appindicator3-dev librsvg2-dev

      - name: Run NAT integration tests
        run: cd src-tauri && RUSTFLAGS="-A warnings" cargo test --test nat_traversal_test --verbose

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: nat-test-results
          path: src-tauri/target/debug/deps/nat_traversal_test-*
